name: native_screenshot_example
description: Demonstrates how to use the native_screenshot plugin.
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  native_screenshot:
    path: ../

flutter:
  uses-material-design: true

  assets:
    - assets/landscape.jpeg
